### ISSUE TITLE
[BUG] Lastest release buttons not registering when pressed?

### ISSUE THREAD

**Issue by AlexN85** [mKenfenheuer/steam-deck-windows-usermode-driver#17]
Hi there

Love the new update. But one thing. Driver states it's started. The sound pops up. Windows and games acknowledges the contoller. But when I press anything nothing doesn't register? No buttons works. Any idea what I'm doing wrong. Thanks and always great work :)

**Comment by mKenfenheuer** [comment]
@AlexN85 can you try the latest release please?
Maybe you need to change the operation mode (in settings) to whitelist or blacklist.

Can you confirm you can see something like `EmulationEnabled changed to: True` in the log?
![grafik](https://user-images.githubusercontent.com/26744396/173345061-1aab72ff-ac86-4411-be21-7116c83bf767.png)



If this is still not working, please upload the support package from the Driver status section (available in the new release).

**Comment by AlexN85** [comment]
> @AlexN85 can you try the latest release please? Maybe you need to change the operation mode (in settings) to whitelist or blacklist.
> 
> Can you confirm you can see something like `EmulationEnabled changed to: True` in the log? ![grafik](https://user-images.githubusercontent.com/26744396/173345061-1aab72ff-ac86-4411-be21-7116c83bf767.png)
> 
> If this is still not working, please upload the support package from the Driver status section (available in the new release).

It worked!!! Changed to blacklist and it worked:)

By the way what does blacklist mean or whitelist mean? Why did I have to change that? :)

Awsome work my friend :)

**Comment by mKenfenheuer** [comment]
There are three modes:

Blacklist: enables the driver if there is no blacklisted process running.
Whitelist: enables the driver if there is any whitelisted process running.
Combined: enables the driver if there is any whitelisted process and no blacklisted process running.

This allows you to only enable the driver if there is a certain game running and so on.
