### ISSUE TITLE
[BUG] Default mapping wrong for D-PAD LEFT

### ISSUE THREAD

**Issue by snailium** [mKenfenheuer/steam-deck-windows-usermode-driver#32]
**Describe the bug**
After installation, the default profile maps D-PAD LEFT as D-PAD UP.

**To Reproduce**
1. Fresh install SWICD
2. Go to GUI configuration tool
3. Go to "Default Profile" -> "Button mappings"
4. Scroll to D-PAD LEFT mapping, see the wrong mapping

**Expected behavior**
D-PAD LEFT should be mapped to D-PAD LEFT

**Screenshots**
N/A

**Debug information**
Driver version: v0.2.5-beta2-f9e0e59-release

**Additional context**
N/A

**Comment by mKenfenheuer** [comment]
Thank you for reporting, has been fixed in [v0.2.6-beta](https://github.com/mKenfenheuer/steam-deck-windows-usermode-driver/releases/tag/v0.2.6-beta)
