### ISSUE TITLE
[BUG] Seems MENU and VIEW buttons are swapped

### ISSUE THREAD

**Issue by snailium** [mKenfenheuer/steam-deck-windows-usermode-driver#33]
**Describe the bug**
The default profile maps seems correct.
- MENU (hamburger) -> MENU
- VIEW (windows) -> VIEW

But in-game it seems MENU button activates VIEW function, and VIEW button activates MENU function.

**To Reproduce**
Steps to reproduce the behavior (Forza Horizon 5):
1. Launch Forza Horizon 5
2. Enter game.
3. Press MENU button, the game pops map interface (which suppose to be activated by VIEW button)
4. Press VIEW button, the game pops menus (which suppose to be activated by MENU button)

Steps to reproduce the behavior (Genshin Impact):
1. Launch Genshin Impact
2. Set input to "Controller"
3. Press MENU button, the game pops chat interface (which suppose to be activated by VIEW button)
4. Press VIEW button, the game pops Paimon menus (which suppose to be activated by MENU button)

**Expected behavior**
VIEW and MENU should be swapped.

**Screenshots**
N/A

**Debug information**
Driver version: v0.2.5-beta2-f9e0e59-release

**Additional context**
N/A

**Comment by mKenfenheuer** [comment]
Thank you for reporting, has been fixed in [v0.2.6-beta](https://github.com/mKenfenheuer/steam-deck-windows-usermode-driver/releases/tag/v0.2.6-beta)
