### ISSUE TITLE
[BUG] cant delete whitelist and blacklist items

### ISSUE THREAD

**Issue by andyktaylor** [mKenfenheuer/steam-deck-windows-usermode-driver#34]
**Describe the bug**

**To Reproduce**

On default profile, click add whitelist, add a program.
Save profile

Now delete program from the default profile 
Save and exit
Log back in, program still shows 

Deleted and reinstalled software and the default profile remembers the program I've whitelisted.

Im on the latest beta

**Comment by chris-neely** [comment]
Same issue here, any work around d we can do while this is resolved? I really need to remove an item from whitelist.

**Comment by mKenfenheuer** [comment]
As a workaround, you can edit the config file.
It's located in your documents folder > SWICD > app_config.conf.

Close the driver, open the file.
Then remove the corresponding whitelist=xxx line.
Save, restart the driver.

**Comment by mKenfenheuer** [comment]
Please check the latest release, it should fix your issues.

https://github.com/mKenfenheuer/steam-deck-windows-usermode-driver/releases/tag/v0.2.7-beta2

**Comment by andyktaylor** [comment]
Thanks, fixed
