### ISSUE TITLE
[BUG] Yuzu emulator B acts as escape button

### ISSUE THREAD

**Issue by joemossjr16** [mKenfenheuer/steam-deck-windows-usermode-driver#41]
Yuzu emulator B acts as escape button. 

**To Reproduce**
1. Go to yuzu
2. Click configure
3. Hit b
4. The windows disappears
**Expected behavior**
To not disappear

**Comment by joemossjr16** [comment]
Also when trying to add a profile a box pops up that asks me to type a name but doesnt do anything. and profiles arent saving

**Comment by mKenfenheuer** [comment]
Please include a support package.

**Comment by joemossjr16** [comment]
[SWICD_Support_637956534768805058.zip](https://github.com/mKenfenheuer/steam-deck-windows-usermode-driver/files/9294518/SWICD_Support_637956534768805058.zip)

**Comment by joemossjr16** [comment]
Done

**Comment by mKenfenheuer** [comment]
Can you try with v0.2.6 please? I have a bad feeling that the 0.2.7 .msi is broken

**Comment by joemossjr16** [comment]
that works perfect now.

**Comment by joemossjr16** [comment]
even the keyboard shortcuts in the back i set. Thanks man!

**Comment by ToXIc-Dev** [comment]
Im still having this issue even when running v0.2.6
