### ISSUE TITLE
[FEATURE] Map + and - Volume Keys to Screen brightness controls (when holding another button down)

### ISSUE THREAD

**Issue by andyktaylor** [mKenfenheuer/steam-deck-windows-usermode-driver#44]
**Is your feature request related to a problem? Please describe.**

I'm trying to find a way to map the screen brightness to the volume buttons as an alternate function.

**Describe the solution you'd like**

Abiliy to map volume buttons in SWICD so that I can change the volume to brightness when holding a alt button

**Describe alternatives you've considered**

I've managed to do it by combining your app with Twinkle Tray ( https://github.com/xanderfrangos/twinkle-tray) but would like to remove having another app running on my Deck, so wondered if there is any other way to do this

**Additional context**

Hope that makes sense, let me know if you need more info

**Comment by mKenfenheuer** [comment]
Unfortunately i do not have any option to grab the plus and minus buttons or intercept them. You can use PowerToys with button actions to map the brightness controls to buttons
