### ISSUE TITLE
Motion control support for Windows Steam Deck

### ISSUE THREAD

**Issue by CasperH2O** [mKenfenheuer/steam-deck-windows-usermode-driver#5]
Hey there! I'm one of the developers of Handheld Companion/Controller Service, someone came up on our Discord sub channel to ask if your app could be combined with ours to make it possible to use motion control on steam deck through Windows. 

Our application currently supports embedded and external motion sensors, external controllers and some other bits. I saw your emulated device does have some gyro and accelerometer in the interface. Perhaps we can talk, combine some effort maybe?

https://github.com/Valkirie/ControllerService

PS Love your resume website design! I'll be sure to open it next time someone from IT walks past me at work, haha.

**Comment by mKenfenheuer** [comment]
Hi, sure! Would you be up for a chat on discord?

Thanks, it indeed has lead to some funny stories and confision!

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: CasperH2O ***@***.***>
Gesendet: Thursday, June 2, 2022 9:40:40 AM
An: mKenfenheuer/steam-deck-windows-usermode-driver ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [mKenfenheuer/steam-deck-windows-usermode-driver] Motion control support for Windows Steam Deck (Issue #5)


Hey there! I'm one of the developers of Handheld Companion/Controller Service, someone came up on our Discord sub channel to ask if your app could be combined with ours to make it possible to use motion control on steam deck through Windows.

Our application currently supports embedded and external motion sensors, external controllers and some other bits. I saw your emulated device does have some gyro and accelerometer in the interface. Perhaps we can talk, combine some effort maybe?

https://github.com/Valkirie/ControllerService

PS Love your resume website design! I'll be sure to open it next time someone from IT walks past me at work, haha.

**Comment by CasperH2O** [comment]
Yes, we are on Discord: https://discord.gg/6UQ4qMMG

![image](https://user-images.githubusercontent.com/14330834/171687209-6fc9b33d-6f4b-45c1-8f4e-d2cdd977dd65.png)
