### ISSUE TITLE
[BUG] Crash

### ISSUE THREAD

**Issue by DocMAX** [mKenfenheuer/steam-deck-windows-usermode-driver#50]
![grafik](https://user-images.githubusercontent.com/5351323/188659189-52a3f6da-593b-4dd1-84e6-7a2c6e17cacc.png)

**Comment by DocMAX** [comment]
Older versions work

**Comment by mKenfenheuer** [comment]
Same Issue as #40. Uninstall completely, then reinstall again.

**Comment by mKenfenheuer** [comment]
Try to uninstall swicd completely, then install again.
