### ISSUE TITLE
Remapping won't work, or even stay?

### ISSUE THREAD

**Issue by Dre2timez** [mKenfenheuer/steam-deck-windows-usermode-driver#6]
so to start, I want to fully disable the touch pad features it is defaulted by. so when I edit the app_config.conf and set everything involving the pad to [None] it doesn't work and it also gets reverted back to the default settings when I open SWICD_Configurator.exe. Also every .exe in your folder is set as admin if it matters.

I love the drivers itself btw Keep up the great work!

Edit: there's also this app that I use for joystick mouse movement called Joyxoff which works flawlessly on 0.1.1 but on 0.1.2 it freezes up when moving the stick ex. making a circle.

**Comment by mKenfenheuer** [comment]
Can you post your config file please?
(Attach it if possible please.)

are you using an executable specific config?

**Comment by Dre2timez** [comment]
[app_config.zip](https://github.com/mKenfenheuer/steam-deck-windows-usermode-driver/files/8836099/app_config.zip)
I was just using the base config that was created.                                                                                                         I also did try pointing my custom settings to a whitelisted program, Microsoft edge, and nothing changed whilst also overwriting my settings.
