### ISSUE TITLE
[BUG] Track pad acts like a Joystick

### ISSUE THREAD

**Issue by XellOwO** [mKenfenheuer/steam-deck-windows-usermode-driver#65]
The trackpads act like a joystick and makes scrolling with the trackpad impossible.
I dont know if this is a feature or a bug but maybe add an option to disable that "function"

Still, Thanks for these free drivers that makes windows usable for the SD

**Comment by SomeoneWasTaken** [comment]
This is a bug, but i dont know how to add the bug label

**Comment by buddie024** [comment]
I hope this is a function. Works great with fps games for micro adjustments on long distance shots. A disable option would be good though.

**Comment by XellOwO** [comment]
Apparently, i can set what happens when i use the trackpad in the profile settings,
So i can disable that "feature"
